# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    environment:
      TEST: << pipeline.project.git_url >>/compare/<< pipeline.git.base_revision >>..<<pipeline.git.revision>>
    working_directory: ~/main
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run: echo "This is pipeline ID << pipeline.id >>"
      - run: echo $TEST

  print-world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Print hello Long"
          command: "echo Hello Long!"

# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      # - print-world:
      #     requires: [say-hello]
